In [1]:
import tensorflow as tf
import pandas as pd

2025-03-13 08:49:34.448484: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741866574.550867    9210 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741866574.587673    9210 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-13 08:49:34.848897: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
FILE_PATH = "data.csv"

In [3]:
def load_csv(csv_file: str, batch_size: int, labels: list, shuffle_size: int):
    dataset = tf.data.experimental.make_csv_dataset(
        csv_file,
        batch_size=batch_size,
        num_epochs=1,
        na_value="?",
        shuffle=True,
        shuffle_buffer_size=shuffle_size
    )

    def extract_labels(features):
        extracted_labels = tuple(features.pop(label) for label in labels)
        return features, extracted_labels

    dataset = dataset.map(extract_labels)

    return dataset

# repare que adaptamos toda essa função para aceitar diversas labels

In [4]:
data = load_csv(
    csv_file=FILE_PATH,
    batch_size=32,
    labels=["class_normal", "class_suspicious", "class_unknown"],
    shuffle_size=10_000
)

2025-03-13 08:49:45.269760: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [5]:
data

<_MapDataset element_spec=(OrderedDict([('Duration', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Src Pt', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Dst Pt', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Packets', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Flows', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Tos', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('numBytes', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('Proto_GRE  ', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Proto_ICMP ', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Proto_TCP  ', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Proto_UDP  ', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Flags_  0x53', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Flags_  0xc2', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('Flags_  0xd2', TensorSpec(shape=(None,), dtype=tf.int32

In [22]:
for features, labels_tuple in data.take(1):
    print("Features:", features)
    print("Labels:", labels_tuple)

Features: OrderedDict([('Duration', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([1.8685123e-05, 1.0007482e-07, 2.1260126e-05, 1.1547095e-07,
       9.0452239e-08, 1.9770550e-05, 0.0000000e+00, 0.0000000e+00,
       1.4433869e-07, 1.3279158e-07, 1.1931998e-07, 1.7451508e-05,
       1.1931998e-07, 1.9245157e-09, 1.6237140e-05, 0.0000000e+00,
       1.4433869e-07, 9.2376759e-08, 1.5973481e-07, 0.0000000e+00,
       0.0000000e+00, 3.3836837e-05, 1.5781029e-07, 3.0792251e-08,
       0.0000000e+00, 1.9753230e-05, 1.5396127e-07, 2.0888694e-05,
       2.5470967e-05, 1.4818771e-07, 1.6935739e-07, 1.2894256e-07],
      dtype=float32)>), ('Src Pt', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([7.84512103e-01, 1.22072175e-01, 7.16441572e-01, 1.22072175e-01,
       9.74364817e-01, 8.57206047e-01, 3.61242086e-01, 2.95964003e-01,
       1.22072175e-01, 8.73395920e-01, 9.16594207e-01, 3.35698482e-04,
       1.22072175e-01, 9.79034126e-01, 3.35698482e-04, 8.95704608e-03,
       7.00099

2025-03-12 14:56:55.549921: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
