In [1]:
import tensorflow as tf

2025-03-12 09:34:23.951239: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-12 09:34:24.034515: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-12 09:34:24.119868: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741782864.217870    8384 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741782864.242116    8384 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-12 09:34:24.417290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [9]:
tensor_tf = tf.random.uniform( # aqui criamos um tensor com essas caracteristicas, aleatoriamente e uniforme
    shape=(3,3), # formato é 3x3
    minval=0,    # valor minimo
    maxval=10,   # valor máximo
    dtype=tf.int32 # tipagem: i32
)

print("=> Tensor da Tensorflow:\n", tensor_tf)

=> Tensor da Tensorflow:
 tf.Tensor(
[[2 4 4]
 [5 9 8]
 [2 3 4]], shape=(3, 3), dtype=int32)


In [10]:
# manipularemos este tensor
tensor_transposto = tf.transpose(tensor_tf)                    # aqui vamos transpor este tensor
print("=> Tensor da tensorflow transposto:\n", tensor_transposto) 

tensor_soma_por_linhas = tf.reduce_sum(tensor_tf, axis=1)      # intuitivamente, somando por linhas
tensor_soma_por_colunas = tf.reduce_sum(tensor_tf, axis=0)     # intuitivamente, somando por colunas
print("\n=> Soma por linha:\n", tensor_soma_por_linhas)
print("\n=> Soma por coluna:\n", tensor_soma_por_colunas)

tensor_expandido = tf.expand_dims(tensor_tf, axis=0)
print("\n=> Tensor com diemnsão expandida:\n", tensor_expandido)

=> Tensor da tensorflow transposto:
 tf.Tensor(
[[2 5 2]
 [4 9 3]
 [4 8 4]], shape=(3, 3), dtype=int32)

=> Soma por linha:
 tf.Tensor([10 22  9], shape=(3,), dtype=int32)

=> Soma por coluna:
 tf.Tensor([ 9 16 16], shape=(3,), dtype=int32)

=> Tensor com diemnsão expandida:
 tf.Tensor(
[[[2 4 4]
  [5 9 8]
  [2 3 4]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
import numpy as np

tensor_np = tensor_tf.numpy()         # convertemos para numpy
print("=> Tensor da Tensorflow convertido para NumPy:\n", tensor_np)

np_mean = np.mean(tensor_np, axis=1)  # média por linha
np_std = np.std(tensor_np)            # desvio padrão


print("\n=> Média por linha:\n", np_mean)
print("\n=> Desvio padrão total:\n", np_std)

=> Tensor da Tensorflow convertido para NumPy:
 [[2 4 4]
 [5 9 8]
 [2 3 4]]

=> Média por linha:
 [3.33333333 7.33333333 3.        ]

=> Desvio padrão total:
 2.3147407395555177


In [19]:
import torch

tensor_torch = torch.randint(0, 10, (3, 3))
print("=> Tensor da PyTorch:\n", tensor_torch)

=> Tensor da PyTorch:
 tensor([[9, 5, 1],
        [6, 3, 7],
        [4, 5, 0]])


In [21]:
# manipulações equivalentes com o pytorch
tensor_torch_transposto = torch.transpose(tensor_torch, 0, 1)
print("=> Tensor da PyTorch transposto:\n", tensor_torch_transposto)

tensor_pt_soma_por_linha = torch.sum(tensor_torch, dim=1)
tensor_pt_soma_por_coluna = torch.sum(tensor_torch, dim=0)
print("\n=> Soma por linha (PyTorch):\n", tensor_pt_soma_por_linha)
print("\n=> Soma por coluna (PyTorch):\n", tensor_pt_soma_por_coluna)

tensor_torch_expandido = tensor_torch.unsqueeze(0)
print("\n=> Tensor com dimensão extra (PyTorch):\n", tensor_torch_expandido)

=> Tensor da PyTorch transposto:
 tensor([[9, 6, 4],
        [5, 3, 5],
        [1, 7, 0]])

=> Soma por linha (PyTorch):
 tensor([15, 16,  9])

=> Soma por coluna (PyTorch):
 tensor([19, 13,  8])

=> Tensor com dimensão extra (PyTorch):
 tensor([[[9, 5, 1],
         [6, 3, 7],
         [4, 5, 0]]])


In [23]:
tensor_tf_from_torch = tf.convert_to_tensor(tensor_torch)

print("=> Tensor da PyTorch convertivo para tensor da tensorflow:\n", tensor_tf_from_torch)

=> Tensor da PyTorch convertivo para tensor da tensorflow:
 tf.Tensor(
[[9 5 1]
 [6 3 7]
 [4 5 0]], shape=(3, 3), dtype=int64)


In [24]:
tensor_torch_from_tf = torch.tensor(tensor_tf.numpy())
print("\n=> Tensor da PyTorch criado a partir do TensorFlow:\n", tensor_torch_from_tf)


=> Tensor da PyTorch criado a partir do TensorFlow:
 tensor([[2, 4, 4],
        [5, 9, 8],
        [2, 3, 4]], dtype=torch.int32)


In [25]:
tensor_tf_from_torch = tf.convert_to_tensor(tensor_torch.numpy())
print("\n=> Tensor da tensorflow criado a partir do PyTorch:\n", tensor_tf_from_torch)


=> Tensor da tensorflow criado a partir do PyTorch:
 tf.Tensor(
[[9 5 1]
 [6 3 7]
 [4 5 0]], shape=(3, 3), dtype=int64)


In [ ]:
# Forçando a barra da tensorflow... (ou quase isso)
big_tensor = tf.random.uniform(
    shape=(500_000, 200), # 500.000 * 200 = 100.000.000
    minval=0,
    maxval=599.1,
    dtype=tf.float64
)

2025-03-12 10:13:07.503712: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 800000000 exceeds 10% of free system memory.
2025-03-12 10:13:07.887239: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 800000000 exceeds 10% of free system memory.


Antes de tudo, vou registrar a análise desse warning:

O erro vem do alocador de memória da CPU do TensorFlow, indicando que a tentativa de alocar 800 MB (800000000 bytes) de memória ultrapassou 10% da memória RAM disponível.

- Se este computador tem 16 GB de RAM total, provavelmente o sistema estava com ~8 GB livres.
- 10% disso seria ~800 MB, exatamente o que o TensorFlow tentou alocar.

In [ ]:
# contornando a situação
big_tensor = tf.random.uniform(
    shape=(500_000, 200), # 500.000 * 200 = os mesmos 100.000.000
    minval=0,
    maxval=599.1,
    dtype=tf.float32 # usando um tipo de float menor
)

Não tem warning mais...

In [52]:
import time

A = tf.random.uniform((100_000, 2000), dtype=tf.float32)
B = tf.random.uniform((2000, 1000), dtype=tf.float32)

# calcular o tempo de execução
start = time.time()
C = tf.matmul(A, B)
end = time.time()

print("Tempo registrado da execução da operação:", end - start, "segundos")

Tempo registrado da execução da operação: 0.9016454219818115 segundos


In [53]:
start_time = time.time()
exp_tensor = tf.exp(big_tensor)  # exponencial
sin_tensor = tf.sin(big_tensor)  # seno
sqrt_tensor = tf.sqrt(big_tensor)  # raiz quadrada
end_time = time.time()

print("Tempo registrado da execução da operação:", end_time - start_time, "segundos")

Tempo registrado da execução da operação: 0.37029480934143066 segundos


In [54]:
# tensor esparso
tensor_esparso = tf.sparse.from_dense(big_tensor)

print("=> Tamanho original:", big_tensor.shape)
print("=> Tamanho esparso:", tensor_esparso.dense_shape)

=> Tamanho original: (500000, 200)
=> Tamanho esparso: tf.Tensor([500000    200], shape=(2,), dtype=int64)


In [57]:
print("=> Tensor Esparso:\n", tensor_esparso)

=> Tensor Esparso:
 SparseTensor(indices=tf.Tensor(
[[     0      0]
 [     0      1]
 [     0      2]
 ...
 [499999    197]
 [499999    198]
 [499999    199]], shape=(99999990, 2), dtype=int64), values=tf.Tensor([ 84.23115  523.32733   13.565045 ... 353.552    506.65637  591.8426  ], shape=(99999990,), dtype=float32), dense_shape=tf.Tensor([500000    200], shape=(2,), dtype=int64))


In [ ]:
# limitar o uso da memória ao tensorflow
# podemos fazer disso uma função ao trabalhar com sistemas que serão deployados modelos baseados em redes neurais profundas e que trabalhem com GPU
gpus = tf.config.experimental.list_physical_devices("GPU") # obs: tensorflor só tem suporte para limitar uso de RAM em GPUs
if gpus:
    try:
        tf.config.experimental.set_virtual_device_configuration(
            gpus[0],
            [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=2048)] # 2048 = 2GB de RAM
        )
    except RuntimeError as erro:
        print(erro)

In [61]:
# verificar antes o uso
import psutil

print(f"Memória disponível: {psutil.virtual_memory().available / 1e9:.2f} GB")

Memória disponível: 0.25 GB
